name: Job Alert

on:
  schedule:
    # Runs every hour from 8am to 11pm Eastern (12-23,0-3 UTC)
    - cron: '0 12-23,0-3 * * *'
  workflow_dispatch:

jobs:
  run-job-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run job alert script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          JOB_TITLE: ${{ secrets.JOB_TITLE }}
          LOCATION: ${{ secrets.LOCATION }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
        run: python src/main.py 